import React, { useState, useRef } from "react";
import "./App.css";
import AppBar from "./components/AppBar";
import CanvasBase from "./components/CanvasBase";
import InspectorPanel from "./components/InspectorPanel";
import Toast from "./components/Toast";
import ErrorBoundary from "./components/ErrorBoundary";
import SideMenu from "./components/SideMenu";
import CodePreviewPanel from "./components/CodePreviewPanel";
import Modal from "./components/Modal";
import VerticalToolRail from "./components/VerticalToolRail";
import { useStore } from "./store/useStore";

function App() {
  const canvasRef = useRef<any>(null);
  const [menuCollapsed, setMenuCollapsed] = useState(false);

  // Bind Zustand layout states
  const codePreviewOpen = useStore((state: any) => state.codePreviewOpen);
  const setCodePreviewOpen = useStore((state: any) => state.setCodePreviewOpen);
  const codeGenResult = useStore((state: any) => state.codeGenResult);
  const proposedRefinedResult = useStore((state: any) => state.proposedRefinedResult);
  const codeGenLoading = useStore((state: any) => state.codeGenLoading);
  const codeGenError = useStore((state: any) => state.codeGenError);
  const refineCode = useStore((state: any) => state.refineCode);
  const generateCode = useStore((state: any) => state.generateCode);
  const acceptRefinement = useStore((state: any) => state.acceptRefinement);
  const rejectRefinement = useStore((state: any) => state.rejectRefinement);

  const isSchemaInspectorOpen = useStore((state: any) => state.isSchemaInspectorOpen);
  const setIsSchemaInspectorOpen = useStore((state: any) => state.setIsSchemaInspectorOpen);
  const localSchema = useStore((state: any) => state.localSchema);

  return (
    <ErrorBoundary>
      <AppBar />
      <div className="app">
        <VerticalToolRail />
        <SideMenu
          collapsed={menuCollapsed}
          onToggle={() => setMenuCollapsed((prev) => !prev)}
          onExportPNG={() => canvasRef.current?.exportToPNG()}
          onExportJSON={() => canvasRef.current?.exportToJSON()}
          onImportJSON={(e) => canvasRef.current?.importJSON(e)}
        />
        <CanvasBase ref={canvasRef} />
        <InspectorPanel />
        <Toast />

        {/* ── Code Preview Panel (slide-over drawer) ── */}
        <CodePreviewPanel
          isOpen={codePreviewOpen}
          onClose={() => setCodePreviewOpen(false)}
          result={codeGenResult}
          proposedRefinedResult={proposedRefinedResult}
          isLoading={codeGenLoading}
          error={codeGenError}
          onRefine={refineCode}
          onRegenerate={generateCode}
          onAcceptRefinement={acceptRefinement}
          onRejectRefinement={rejectRefinement}
        />

        {/* Schema Inspector Modal */}
        {isSchemaInspectorOpen && (
          <Modal
            title={
              <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
                <div
                  style={{
                    width: "30px",
                    height: "30px",
                    borderRadius: "8px",
                    background: "rgba(99,102,241,0.15)",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                  }}
                >
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#818cf8" strokeWidth="2.5">
                    <path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z" />
                  </svg>
                </div>
                <span style={{ fontSize: "14px", fontWeight: "700", color: "var(--text-primary)" }}>
                  UI Schema Inspector
                </span>
              </div>
            }
            onClose={() => setIsSchemaInspectorOpen(false)}
            footer={
              <button
                type="button"
                className="side-menu__btn-secondary"
                onClick={() => setIsSchemaInspectorOpen(false)}
              >
                Close
              </button>
            }
          >
            <p style={{ margin: "0 0 12px", fontSize: "12px", color: "var(--text-muted)", lineHeight: "1.5" }}>
              This is the raw, frontend-extracted semantic AST generated by the canvas transformer. It is normalized and enriched downstream by the AI generation pipeline.
            </p>
            <pre
              style={{
                margin: 0,
                padding: "14px",
                background: "var(--bg)",
                border: "1px solid var(--border)",
                borderRadius: "var(--radius-sm)",
                fontSize: "11px",
                color: "var(--text-primary)",
                fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
                overflowX: "auto",
                maxHeight: "380px",
              }}
            >
              {JSON.stringify(localSchema, null, 2)}
            </pre>
          </Modal>
        )}
      </div>
    </ErrorBoundary>
  );
}

export default App;
